-- Drop the table if it already exists to ensure the schema is correct
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS subscribers;
DROP TABLE IF EXISTS digest_logs;
DROP TABLE IF EXISTS digest_feedback;
DROP TABLE IF EXISTS digest_sent_articles;

-- Required for gen_random_uuid() on a clean database
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Create the articles table
CREATE TABLE articles (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  summary text not null,
  content text not null,
  category text not null,
  source_name text,
  source_url text,
  original_url text,
  image_url text,
  is_featured boolean default false,
  tags text[],
  published_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert dummy data so the homepage and article pages render correctly
INSERT INTO articles (slug, title, summary, content, category, source_name, source_url, original_url, image_url, is_featured, tags, published_at)
VALUES
(
  'zero-day-exploit-vpn',
  'Zero-Day Exploit Found in Popular VPN',
  'Attackers are exploiting a new vulnerability in market-leading VPN software. Here is how to patch it immediately.',
  '# The Zero-Day Crisis\n\nSecurity researchers have uncovered a critical 0-day vulnerability in widely used enterprise VPN software. Threat actors are actively exploiting this in the wild to bypass authentication and gain full network access.\n\n## Mitigation Steps\n- Update to the latest patch immediately.\n- Rotate VPN credentials.\n- Monitor traffic logs for suspicious outbound connections.',
  'Security',
  '7secure',
  'https://7secure.pages.dev',
  'https://7secure.pages.dev/articles/zero-day-exploit-vpn',
  '/cover.avif',
  true,
  ARRAY['vulnerability', 'vpn', '0-day'],
  NOW() - interval '1 day'
),
(
  'rise-of-ai-phishing',
  'The Rise of AI-Generated Phishing',
  'How threat actors are utilizing LLMs to craft hyper-personalized and error-free phishing campaigns at scale.',
  '# AI and Social Engineering\n\nGenerative AI models have democratized the ability to write high-quality, localized phishing emails. Unlike the grammatically flawed emails of the past, these new threats perfectly mimic internal company communications.\n\n## Defense Strategies\n1. Move beyond simple text analysis for email security.\n2. Implement phishing-resistant MFA (like FIDO2 keys).\n3. Train employees to verify unusual financial requests out of band.',
  'Agents',
  'Jane Doe',
  'https://example.com',
  'https://example.com/ai-phishing',
  '/cover.avif',
  false,
  ARRAY['ai', 'phishing', 'threat-intel'],
  NOW() - interval '2 days'
);
CREATE TABLE subscribers (
  id uuid default gen_random_uuid() primary key,
  email text unique not null,
  role text,
  interests text[],
  confirmed boolean default true,
  unsubscribed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE digest_logs (
  id bigint generated by default as identity primary key,
  article_count integer not null,
  subscriber_count integer not null,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE digest_feedback (
  id bigint generated by default as identity primary key,
  email text not null,
  rating smallint not null check (rating between 1 and 5),
  context text default 'daily_digest_email',
  feedback_source text default 'email_star_click',
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE digest_sent_articles (
  article_slug text primary key,
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX digest_sent_articles_sent_at_idx ON digest_sent_articles(sent_at DESC);
