import type { RawFeedItem } from "../types";

const REGULATORY_KEYWORDS = new Set([
  "regulation", "regulatory", "compliance", "gdpr", "ccpa", "cpra", "hipaa", "sox",
  "sarbanes-oxley", "pci-dss", "pci dss", "iso 27001", "iso27001", "nist", "csf",
  "cybersecurity framework", "directive", "nis2", "digital operational resilience act",
  "dora", "schrems", "privacy shield", "data protection", "personal data",
  "breach notification", "incident reporting", "audit", "assessment", "certification",
  "accreditation", "standard", "framework", "governance", "risk management",
  "third-party risk", "vendor risk", "supply chain risk", "due diligence", "sla",
  "contractual", "legal obligation", "statutory", "mandatory", "enforceable",
  "penalty", "fine", "sanction", "litigation", "lawsuit", "court", "ruling",
  "precedent", "jurisdiction", "sovereignty", "data localization", "cross-border",
  "transfer mechanism", "adequacy decision", "binding corporate rules", "bcr",
  "code of conduct", "ethical guideline", "ai act", "artificial intelligence act",
  "algorithmic accountability", "executive order", "federal", "state law", "bill",
  "legislation", "congress", "parliament", "commission", "authority", "supervisory",
  "ombudsman", "attorney general", "sec", "ftc", "fcc", "finra", "eba", "edpb",
  "ico", "cnil", "bsi", "acsc", "cyber security agency", "policy update", "guidance",
  "advisory", "circular", "memorandum", "white paper", "green paper",
  "public consultation", "stakeholder", "industry standard", "best practice framework",
  "control objective", "maturity model", "cmmi", "cobit", "itil", "soc 2", "soc2",
  "type ii", "fedramp", "stateramp", "cmmc", "dfars", "itar", "ear", "export control",
  "sanctions", "ofac", "aml", "kyc", "transaction monitoring", "suspicious activity",
  "sar", "pep", "beneficial ownership", "corporate transparency", "whistleblower",
  "protected disclosure", "retaliation", "wrongdoing", "fraud", "corruption",
  "bribery", "fcpa", "uk bribery act", "anti-corruption", "conflict of interest",
  "insider trading", "market abuse", "misrepresentation", "false statement",
  "perjury", "obstruction", "evidence tampering", "spoliation", "chain of custody",
  "forensic", "expert witness", "subpoena", "warrant", "search and seizure",
  "wiretap", "surveillance", "monitoring", "employee monitoring", "workplace privacy",
  "biometric", "facial recognition", "cctv", "data retention", "deletion",
  "right to be forgotten", "erasure", "portability", "access request", "dsar",
  "subject access", "consent", "opt-in", "opt-out", "cookie", "tracking",
  "profiling", "automated decision", "legitimate interest", "data controller",
  "data processor", "joint controller", "representative", "dpo",
  "data protection officer", "privacy impact", "dpia", "privacy by design",
  "privacy by default", "transparency", "notice", "fair processing", "lawful basis",
  "special category", "sensitive data", "health data", "financial data",
  "criminal record", "child protection", "parental consent", "age verification",
  "identity verification", "knowledge-based", "document verification",
  "liveness detection", "digital identity", "eidas", "qualified certificate",
  "electronic signature", "timestamp", "long-term validation", "archiving",
  "electronic record", "authenticity", "integrity", "non-repudiation",
  "legal admissibility", "evidentiary value", "discovery", "ediscovery", "hold",
  "preservation", "retention schedule", "classification", "handling", "marking",
  "dissemination", "need-to-know", "compartmentalization", "segmentation",
  "isolation", "air gap", "physical security", "personnel security",
  "background check", "security clearance", "vetting", "insider threat",
  "malicious insider", "negligent insider", "compromised insider",
  "departing employee", "offboarding", "access revocation", "privileged access",
  "standing access", "just-in-time", "ephemeral", "break-glass", "emergency access",
  "recertification", "revalidation", "periodic review", "access certification",
  "identity governance", "iga", "iam", "identity and access", "sso", "federation",
  "saml", "oauth", "openid", "mfa", "2fa", "strong authentication", "passwordless",
  "passkey", "fido", "webauthn", "biometric authentication", "behavioral",
  "risk-based", "step-up", "continuous authentication", "session management",
  "timeout", "concurrent session", "session fixation", "hijacking",
  "credential stuffing", "brute force", "password policy", "complexity", "rotation",
  "history", "reuse", "sharing", "vault", "secret management", "password manager",
  "enterprise password", "privileged password", "application password",
  "service account", "managed identity", "workload identity", "pod identity",
  "irsa", "federation", "trust relationship", "cross-account", "tenant isolation",
  "multi-tenant", "customer data isolation", "row-level security", "column-level",
  "masking", "redaction", "tokenization", "anonymization", "pseudonymization",
  "encryption", "key management", "hsm", "kms", "certificate", "tls", "ssl",
  "cipher suite", "perfect forward secrecy", "quantum-resistant", "post-quantum",
  "crypto agility", "algorithm deprecation", "vulnerability disclosure",
  "coordinated disclosure", "responsible disclosure", "bug bounty", "safe harbor",
  "cvd", "cve", "cwe", "cvss", "epss", "kev", "known exploited", "cisa binding",
  "directive", "emergency", "critical infrastructure", "sector-specific",
  "ot security", "ics security", "scada", "industrial control",
  "operational technology", "functional safety", "safety instrumented",
  "iec 62443", "nerc cip", "pipeline security", "maritime", "aviation", "space",
  "defense", "military", "national security", "classified", "top secret", "secret",
  "confidential", "unclassified", "cui", "controlled unclassified",
  "distribution statement", "handling caveat", "releasability", "nato", "allied",
  "five eyes", "intelligence sharing", "fusion center", "information sharing",
  "isac", "sector isac", "automotive isac", "financial isac", "healthcare isac",
  "threat intel sharing", "stix", "taxi", "misp", "openioc", "yara", "sigma",
  "kql", "spl", "rule", "detection", "indicator", "ioc", "ttp", "mitre", "att&ck",
  "d3fend", "shield", "engagement", "adversary emulation", "purple team",
  "atomic red", "caldera", "prelude", "operator", "strain", "custom tool",
  "malware family", "apt", "nation-state", "e-crime", "hacktivist", "insider",
  "supply chain", "software supply", "build pipeline", "ci/cd", "devsecops",
  "shift left", "security by design", "secure sdlc", "owasp", "asvs", "masvs",
  "top 10", "proactive control", "cheat sheet", "testing guide", "zap", "burp",
  "nessus", "qualys", "rapid7", "tenable", "crowdstrike", "sentinelone",
  "carbon black", "microsoft defender", "crowd strike", "palo alto", "fortinet",
  "checkpoint", "sophos", "trend micro", "kaspersky", "mcafee", "symantec",
  "broadcom", "proofpoint", "mimecast", "darktrace", "vectra", "extrahop",
  "corelight", "zeek", "suricata", "snort", "wireshark", "tcpdump",
  "network detection", "ndr", "network traffic analysis", "nta", "user behavior",
  "ueba", "siem", "soar", "xdr", "edr", "mdr", "managed detection", "soc",
  "security operations", "csirt", "cert", "cirt", "incident response", "forensics",
  "malware analysis", "reverse engineering", "threat hunting", "proactive defense",
  "deception", "honeypot", "honeynet", "trap", "decoy", "breadcrumb", "lure",
  "credential", "honeytoken", "canary", "tripwire", "behavioral analytics",
  "anomaly detection", "machine learning", "ai-powered", "autonomous",
  "self-healing", "zero trust", "microsegmentation", "software-defined perimeter",
  "sdp", "beyondcorp", "identity-aware proxy", "context-aware", "device trust",
  "health attestation", "compliance check", "conditional access", "app proxy",
  "reverse proxy", "waf", "waap", "api security", "bot management",
  "ddos protection", "cdn", "edge security", "sase", "sd-wan", "secure access",
  "casb", "swg", "secure web gateway", "remote browser", "isolation", "sandbox",
  "virtualization", "container security", "kubernetes security", "docker",
  "image scanning", "runtime protection", "admission controller", "opa",
  "kyverno", "gatekeeper", "policy engine", "infrastructure as code", "terraform",
  "cloudformation", "arm", "pulumi", "ansible", "puppet", "chef",
  "compliance as code", "policy as code", "security as code", "gitops", "argo",
  "flux", "sealed secret", "external secret", "vault integration",
  "dynamic secret", "database secret", "rotation", "lease", "ttl", "revocation",
  "auditing", "logging", "monitoring", "observability", "telemetry", "trace",
  "span", "metric", "log aggregation", "siem ingestion", "data lake",
  "security data", "data warehouse", "analytics", "dashboard", "kpi", "okr",
  "maturity assessment", "capability model", "benchmark", "scoring", "rating",
  "comparison", "peer", "industry average", "best-in-class", "leader", "laggard",
  "gap analysis", "roadmap", "strategy", "transformation", "modernization",
  "digital transformation", "cloud migration", "lift and shift", "replatform",
  "refactor", "rearchitect", "repurchase", "retire", "retain", "hybrid",
  "multi-cloud", "cloud-native", "serverless", "faas", "paas", "saas", "iaas",
  "draas", "bcdr", "backup", "disaster recovery", "business continuity",
  "resilience", "high availability", "fault tolerance", "redundancy", "failover",
  "load balancing", "geographic distribution", "edge computing", "fog computing",
  "iot security", "ot security", "iiot", "smart city", "connected vehicle",
  "autonomous driving", "medical device", "wearable", "implantable", "rfid",
  "nfc", "bluetooth", "zigbee", "z-wave", "lora", "sigfox", "5g security",
  "mobile security", "app security", "mam", "mdm", "uem", "byod", "cope",
  "containerization", "virtual desktop", "remote access", "vpn",
  "zero trust network", "ztna", "bastion", "jump server", "privileged session",
  "session recording", "keystroke logging", "screen capture", "application control",
  "whitelisting", "blacklisting", "graylisting", "reputation", "trust scoring",
  "risk scoring", "vulnerability scoring", "threat scoring", "impact scoring",
  "likelihood", "exposure", "attack surface", "asset inventory", "cmdb",
  "cmba", "itam", "configuration management", "baseline", "hardening",
  "cis benchmark", "stig", "security baseline", "gold image", "template",
  "provisioning", "orchestration", "automation", "runbook", "playbook",
  "standard operating procedure", "sop", "checklist", "template", "guideline",
  "policy", "procedure", "standard", "baseline", "control", "safeguard",
  "countermeasure", "compensating control", "mitigation", "remediation",
  "workaround", "temporary fix", "permanent fix", "patch management",
  "vulnerability management", "threat management", "risk management",
  "issue management", "change management", "release management",
  "service management", "itil", "itsm", "itsm", "ticketing", "incident ticket",
  "service request", "change request", "problem record", "knowledge article",
  "wiki", "documentation", "runbook", "playbook", "standard", "guideline",
  "training", "awareness", "phishing simulation", "security culture",
  "human factor", "social engineering", "pretexting", "baiting", "quid pro quo",
  "tailgating", "shoulder surfing", "dumpster diving", "physical intrusion",
  "social engineering", "voice phishing", "vishing", "smishing", "qrishing",
  "deepfake", "synthetic media", "impersonation", "business email compromise",
  "bec", "email compromise", "invoice fraud", "payment fraud", "wire fraud",
  "supply chain fraud", "procurement fraud", "insurance fraud", "healthcare fraud",
  "tax fraud", "identity fraud", "account takeover", "ato", "new account fraud",
  "synthetic identity", "first-party fraud", "third-party fraud", "friendly fraud",
  "chargeback", "dispute", "reversal", "refund", "return", "warranty",
  "guarantee", "indemnification", "liability", "limitation", "exclusion",
  "waiver", "release", "settlement", "agreement", "contract", "terms",
  "conditions", "sla", "slo", "sla breach", "penalty clause",
  "liquidated damages", "force majeure", "act of god", "frustration",
  "impossibility", "hardship", "renegotiation", "termination", "suspension",
  "novation", "assignment", "delegation", "subcontracting", "outsourcing",
  "offshoring", "nearshoring", "managed service", "msp", "mssp", "consulting",
  "advisory", "assessment", "audit", "penetration test", "red team", "blue team",
  "purple team", " tabletop", "simulation", "drill", "exercise", "scenario",
  "after-action", "lessons learned", "continuous improvement", "kaizen", "lean",
  "six sigma", "capability maturity", "cmmi", "assessment", "appraisal",
  "certification", "accreditation", "authorization", "ato", "c&a", "diacap",
  "rmf", "nist 800-37", "nist 800-53", "nist 800-171", "nist 800-172",
  "nist csf", "iso 27001", "iso 27002", "iso 27017", "iso 27018", "iso 27701",
  "iso 22301", "iso 31000", "iso 9001", "soc 1", "soc 2", "soc 3", "pci dss",
  "pci 3ds", "pci spoc", "pci pa-dss", "pa-dss", "hipaa", "HITECH", "glba",
  "ffiec", "basel", "sox", "gdpr", "lgpd", "pdpa", "poPI", "appi", "pIPeda",
  "ccpa", "cpra", "vcdpa", "cpa", "ucopa", "shield act", "coppa", "ferpa",
  "idea", "section 508", "ada", "aca", "hipaa omnibus", " breach notification rule",
  "enforcement rule", "privacy rule", "security rule", "transaction rule",
  "identifier rule", "operating rule", "code set", "standard",
  "implementation specification", "addressable", "required", "meaningful use",
  "promoting interoperability", "mips", "macra", "quality payment", "value-based",
  "bundled payment", "shared savings", "accountable care", "patient engagement",
  "health information exchange", "hie", "carequality", "commonwell", "tefca",
  "trusted exchange", "information blocking", "api requirement", "patient access",
  "provider directory", "payer-to-payer", "prior authorization",
  "admission notification", "discharge summary", "clinical summary",
  "transition of care", "care plan", "advance directive", "power of attorney",
  "healthcare proxy", "surrogate decision", "informed consent", "clinical trial",
  "human subject", "irb", "ethical review", "data safety", "monitoring board",
  "adverse event", "serious adverse", "suspected unexpected", "susar",
  "pharmacovigilance", "drug safety", "device safety", "maude", "medwatch",
  "vigibase", "who-umc", "ich", "gcp", "gmp", "glp", "gdp", "gsp", "qms",
  "quality system", "design control", "risk management", "iso 14971",
  "iec 62304", "iec 62366", "usability", "biocompatibility", "sterilization",
  "validation", "verification", "software validation", "csv", "computer system",
  "electronic record", "electronic signature", "21 cfr part 11", "annex 11",
  "data integrity", "alcoa+", "complete", "consistent", "enduring", "available",
  "attributable", "legible", "contemporaneous", "original", "accurate",
  "metadata", "audit trail", "system generated", "user-generated", "backup",
  "archive", "retrieval", "restoration", "disaster recovery", "business continuity",
  "validation protocol", "iq", "oq", "pq", "installation", "operational",
  "performance", "qualification", "commissioning", "qualification",
  "requalification", "periodic review", "revalidation", "change control",
  "deviation", "capa", "corrective action", "preventive action", "root cause",
  "investigation", "impact assessment", "risk assessment", "hazard analysis",
  "fmea", "fault tree", "event tree", "bow-tie", "layer of protection", "lopa",
  "safety instrumented", "sil", "pil", "qul", "cyber security", "cyber-physical",
  "functional safety", "safety instrumented", "safety lifecycle",
  "security lifecycle", "convergence", "integration", "alignment",
  "harmonization", "standardization", "interoperability", "portability",
  "scalability", "performance", "availability", "reliability", "maintainability",
  "usability", "accessibility", "sustainability", "resilience", "adaptability",
  "flexibility", "agility", "innovation", "digitalization", "automation",
  "intelligence", "analytics", "machine learning", "artificial intelligence",
  "deep learning", "neural network", "natural language", "computer vision",
  "robotic process", "rpa", "intelligent automation", "hyperautomation",
  "low-code", "no-code", "citizen developer", "pro-code", "full-code", "devops",
  "devsecops", "gitops", "mlops", "aiops", "dataops", "platform engineering",
  "site reliability", "sre", "chaos engineering", "resilience engineering",
  "observability engineering", "security engineering", "privacy engineering",
  "trust engineering", "safety engineering", "reliability engineering",
  "performance engineering", "capacity planning", "load testing", "stress testing",
  "spike testing", "soak testing", "chaos testing", "failure injection",
  "game day", "fire drill", "incident command", "ics", "nims", " unified command",
  "command staff", "operations", "planning", "logistics", "finance", "situation",
  "resource", "demobilization", "recovery", "restoration", "reconstitution",
  "return to normal", "new normal", "lessons learned", "after-action",
  "improvement plan", "corrective action", "preventive action", "management review",
  "board reporting", "executive summary", "risk report", "security posture",
  "maturity score", "benchmark", "peer comparison", "industry ranking",
  "analyst rating", "gartner", "forrester", "idc", "frost", "kuppinger", "ovum",
  "451", "sis", "metricstream", "rsa", "ibm", "microsoft", "google", "amazon",
  "oracle", "sap", "salesforce", "serviceNow", "splunk", "elastic", "datadog",
  "dynatrace", "new relic", "appdynamics", "riverbed", "extrahop", "corelight",
  "vectra", "darktrace", "sentinelone", "crowdstrike", "palo alto", "fortinet",
  "checkpoint", "juniper", "cisco", "f5", "akamai", "cloudflare", "fastly",
  "imperva", "radware", "arbor", "netscout", "nokia", "ericsson", "huawei",
  "zte", "samsung", "lg", "sony", "panasonic", "toshiba", "fujitsu", "nec",
  "hitachi", "mitsubishi", "siemens", "bosch", "abb", "schneider", "honeywell",
  "johnson", "utc", "raytheon", "lockheed", "northrop", "boeing",
  "general dynamics", "bae", "saab", "thales", "airbus", "leonardo",
  "finmeccanica", "rolls-royce", "bombardier", "embraer", "cae", "l3", "harris",
  "l3harris", "caci", "sais", "booz allen", "deloitte", "pwc", "ey", "kpmg",
  "accenture", "ibm", "cognizant", "infosys", "tcs", "wipro", "hcl",
  "tech mahindra", "capgemini", "atos", "sopra", "steria", "cgi", "csc", "dxc",
  "ntt", "fujitsu", "hitachi", "nec", "toshiba", "panasonic", "sony", "samsung",
  "lg", "hyundai", "kia", "toyota", "honda", "nissan", "mazda", "subaru",
  "mitsubishi", "suzuki", "isuzu", "daihatsu", "hino", "yamaha", "kawasaki",
  "suzuki", "honda", "bmw", "mercedes", "audi", "volkswagen", "porsche", "opel",
  "seat", "skoda", "bentley", "lamborghini", "bugatti", "ducati", "scania",
  "man", "daf", "iveco", "volvo", "renault", "peugeot", "citroen", "ds",
  "alpina", "brabus", "abt", "mtm", "ruf", "gemballa", "9ff", "techart",
  "mansory", "novitec", "carbonfiber", "vorsteiner", "hre", "bbs", "oz",
  "enkei", "volk", "rays", "weds", "work", "ssr", "tws", "yokohama", "toyo",
  "bridgestone", "michelin", "continental", "pirelli", "dunlop", "goodyear",
  "hankook", "kumho", "nexen", "giti", "maxxis", "federal", "achilles",
  "nankang", "linglong", "triangle", "sentury", "aeolus", "prinx", "cooper",
  "mastercraft", "general", "uniroyal", "bf goodrich", "falken", "nitto",
  "toyo", "yokohama", "advAN", "yokohama", "toyo", "bridgestone", "michelin",
  "continental", "pirelli", "dunlop", "goodyear", "hankook", "kumho", "nexen",
  "giti", "maxxis", "federal", "achilles", "nankang", "linglong", "triangle",
  "sentury", "aeolus", "prinx", "cooper", "mastercraft", "general", "uniroyal",
  "bf goodrich", "falken", "nitto", "toyo", "yokohama", "advAN",
  "regulatory-watch", "compliance", "audit", "certification", "standard",
  "framework", "guideline", "policy", "legislation", "directive", "advisory",
  "cisa", "enisa", "nist", "gdpr", "iso"
]);

const REGULATORY_SOURCES = new Set([
  "NIST CSRC",
  "CISA Alerts",
  "CERT-EU",
  "Cyber.gc.ca",
  "CERT NZ",
  "ASD Cyber",
  "ENISA",
  "ANSSI"
]);

export const isRegulatoryContent = (item: RawFeedItem): boolean => {
  const signal = `${item.title} ${item.summary} ${item.sourceSnippet || ""}`.toLowerCase();

  // Source-based classification (high confidence)
  if (REGULATORY_SOURCES.has(item.sourceName)) {
    return true;
  }

  // Keyword-based classification
  let keywordHits = 0;
  for (const keyword of REGULATORY_KEYWORDS) {
    if (signal.includes(keyword.toLowerCase())) {
      keywordHits += 1;
      // Early return on strong signals
      if (keywordHits >= 3) {
        return true;
      }
    }
  }

  // Classification if at least 2 regulatory keywords found
  return keywordHits >= 2;
};

export const applyRegulatoryTag = (tags: string[]): string[] => {
  const normalized = tags.map((t) => t.toLowerCase().trim());
  if (normalized.includes("regulatory-watch")) {
    return tags;
  }
  return [...tags, "regulatory-watch"];
};
