import type { RSSSource } from "../types";

export const RSS_SOURCES: RSSSource[] = [
  { name: "Abuse.ch", url: "https://abuse.ch/feeds/", category: "threat-intel" },
  { name: "Malwarebytes", url: "https://blog.malwarebytes.com/feed/", category: "threat-intel" },
  { name: "Talos Intelligence", url: "https://blog.talosintelligence.com/atom.xml", category: "threat-intel" },
  { name: "VirusTotal", url: "https://blog.virustotal.com/atom.xml", category: "threat-intel" },
  { name: "SANS ISC", url: "https://isc.sans.edu/rssfeed.xml", category: "threat-intel" },
  { name: "Naked Security", url: "https://nakedsecurity.sophos.com/feed/", category: "threat-intel" },
  { name: "Sophos News", url: "https://news.sophos.com/en-us/feed/", category: "threat-intel" },
  { name: "AlienVault OTX", url: "https://otx.alienvault.com/feeds/", category: "threat-intel" },
  { name: "Check Point Research", url: "https://research.checkpoint.com/feed/", category: "threat-intel" },
  { name: "Emerging Threats", url: "https://rules.emergingthreats.net/rss", category: "threat-intel" },
  { name: "Threatpost", url: "https://threatpost.com/feed/", category: "threat-intel" },
  { name: "Cisco Umbrella", url: "https://umbrella.cisco.com/blog/rss.xml", category: "threat-intel" },
  { name: "Palo Alto Unit42", url: "https://unit42.paloaltonetworks.com/feed/", category: "threat-intel" },
  { name: "URLhaus", url: "https://urlhaus.abuse.ch/downloads/rss/", category: "threat-intel" },
  { name: "Akamai Security", url: "https://www.akamai.com/blog/security/rss.xml", category: "threat-intel" },
  { name: "Bitdefender Labs", url: "https://www.bitdefender.com/blog/api/rss/labs/", category: "threat-intel" },
  { name: "CrowdStrike", url: "https://www.crowdstrike.com/blog/feed/", category: "threat-intel" },
  { name: "Fortinet", url: "https://www.fortinet.com/blog.rss", category: "threat-intel" },
  { name: "GreyNoise", url: "https://www.greynoise.io/blog/rss.xml", category: "threat-intel" },
  { name: "Kaspersky", url: "https://www.kaspersky.com/blog/rss.xml", category: "threat-intel" },
  { name: "Mandiant", url: "https://www.mandiant.com/resources/rss.xml", category: "threat-intel" },
  { name: "Recorded Future", url: "https://www.recordedfuture.com/blog/rss.xml", category: "threat-intel" },
  { name: "Shadowserver", url: "https://www.shadowserver.org/feed/", category: "threat-intel" },
  { name: "Trend Micro", url: "https://www.trendmicro.com/vinfo/us/security/news.rss", category: "threat-intel" },

  { name: "VMware Security", url: "https://blogs.vmware.com/security/feed/", category: "vulnerabilities" },
  { name: "OWASP", url: "https://owasp.org/feed.xml", category: "vulnerabilities" },
  { name: "Daily Swig", url: "https://portswigger.net/daily-swig/rss.xml", category: "vulnerabilities" },
  { name: "Security StackExchange", url: "https://security.stackexchange.com/feeds", category: "vulnerabilities" },
  { name: "CVE StackExchange", url: "https://security.stackexchange.com/feeds/tag?tagnames=cve", category: "vulnerabilities" },
  { name: "Snyk", url: "https://snyk.io/blog/rss.xml", category: "vulnerabilities" },
  { name: "F5 Security", url: "https://www.f5.com/services/resources/rss.xml", category: "vulnerabilities" },
  { name: "Rapid7", url: "https://www.rapid7.com/blog/rss.xml", category: "vulnerabilities" },

  { name: "Ars Technica", url: "https://arstechnica.com/feed/", category: "industry-news" },
  { name: "AWS Security", url: "https://aws.amazon.com/blogs/security/feed/", category: "industry-news" },
  { name: "Cloudflare Security", url: "https://blog.cloudflare.com/tag/security/rss/", category: "industry-news" },
  { name: "Google Cloud Security", url: "https://cloud.google.com/blog/topics/security/rss.xml", category: "industry-news" },
  { name: "Cryptomator", url: "https://cryptomator.org/blog/feed/", category: "industry-news" },
  { name: "GitHub Changelog", url: "https://github.blog/changelog/", category: "industry-news" },
  { name: "Hacker News", url: "https://hnrss.org/frontpage", category: "industry-news" },
  { name: "Krebs on Security", url: "https://krebsonsecurity.com/feed/", category: "industry-news" },
  { name: "Let's Encrypt", url: "https://letsencrypt.org/feed/", category: "industry-news" },
  { name: "Medium Cybersecurity", url: "https://medium.com/feed/tag/cybersecurity", category: "industry-news" },
  { name: "Darknet Diaries", url: "https://podcast.darknetdiaries.com/rss", category: "industry-news" },
  { name: "Risky Business", url: "https://risky.biz/feed/", category: "industry-news" },
  { name: "TechCrunch Security", url: "https://techcrunch.com/tag/security/feed/", category: "industry-news" },
  { name: "The Hacker News", url: "https://thehackernews.com/feeds/posts/default?alt=rss", category: "industry-news" },
  { name: "BleepingComputer", url: "https://www.bleepingcomputer.com/rss/", category: "industry-news" },
  { name: "CSO Online", url: "https://www.csoonline.com/index.rss", category: "industry-news" },
  { name: "Dark Reading", url: "https://www.darkreading.com/rss.xml", category: "industry-news" },
  { name: "EFF", url: "https://www.eff.org/rss/", category: "industry-news" },
  { name: "Elastic Security", url: "https://www.elastic.co/blog/tag/security?format=rss", category: "industry-news" },
  { name: "Microsoft Security", url: "https://www.microsoft.com/security/blog/feed/", category: "industry-news" },
  { name: "r/cybersecurity", url: "https://www.reddit.com/r/cybersecurity/.rss", category: "industry-news" },
  { name: "Schneier on Security", url: "https://www.schneier.com/blog/atom.xml", category: "industry-news" },
  { name: "SecurityWeek", url: "https://www.securityweek.com/rss.xml", category: "industry-news" },
  { name: "Smashing Security", url: "https://www.smashingsecurity.com/rss", category: "industry-news" },
  { name: "Splunk Security", url: "https://www.splunk.com/en_us/blog/security.html?format=rss", category: "industry-news" },
  { name: "The Cyber Wire", url: "https://www.thecyberwire.com/rss/news.xml", category: "industry-news" },
  { name: "The Register", url: "https://www.theregister.com/headlines.atom", category: "industry-news" },
  { name: "Vice Cybersecurity", url: "https://www.vice.com/en/topic/cybersecurity/rss", category: "industry-news" },
  { name: "Wired Security", url: "https://www.wired.com/feed/category/security/latest/rss", category: "industry-news" },
  { name: "ZDNet Security", url: "https://www.zdnet.com/topic/security/rss.xml", category: "industry-news" },
  { name: "Netlas", url: "https://netlas.io/blog/rss.xml", category: "industry-news" },

  { name: "IACR ePrint", url: "https://eprint.iacr.org/rss/", category: "research" },
  { name: "arXiv CS.CC", url: "https://export.arxiv.org/rss/cs.CC", category: "research" },
  { name: "arXiv CS.CR", url: "https://export.arxiv.org/rss/cs.CR", category: "research" },
  { name: "Google Research", url: "https://research.google/blog/rss/", category: "research" },

  { name: "DeepMind", url: "https://deepmind.com/blog/rss.xml", category: "ai-security" },
  { name: "HuggingFace", url: "https://huggingface.co/blog/rss.xml", category: "ai-security" },
  { name: "OpenAI Blog", url: "https://openai.com/blog/rss/", category: "ai-security" },
  { name: "Alignment Forum", url: "https://www.alignmentforum.org/feeds.rss", category: "ai-security" },
  { name: "Anthropic", url: "https://www.anthropic.com/index.rss", category: "ai-security" },
  { name: "Center for AI Safety", url: "https://www.centerforaisafety.org/rss", category: "ai-security" },

  { name: "CERT-EU", url: "https://cert.europa.eu/rss", category: "government" },
  { name: "NIST CSRC", url: "https://csrc.nist.gov/feeds/news.xml", category: "government" },
  { name: "Cyber.gc.ca", url: "https://cyber.gc.ca/en/rss", category: "government" },
  { name: "CERT NZ", url: "https://www.cert.govt.nz/rss", category: "government" },
  { name: "CISA Alerts", url: "https://www.cisa.gov/uscert/ncas/alerts.xml", category: "government" },
  { name: "ASD Cyber", url: "https://www.cyber.gov.au/news-and-events/rss-feeds", category: "government" },
  { name: "ENISA", url: "https://www.enisa.europa.eu/feed/", category: "government" },
  { name: "ANSSI", url: "https://www.ssi.gouv.fr/feed/", category: "government" }
];
